[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10

[deploy.env]
NODE_ENV = "production"
